spring.application.name=bplus-backend
spring.datasource.url=jdbc:mysql://localhost:3306/b_plus_db
spring.datasource.username=root
spring.datasource.password=Sima@1432

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pratiknaskar10@gmail.com
spring.mail.password=lqdj ozny lkjm ooeg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true